### ISSUE TITLE
make docker 时出错

### ISSUE THREAD

**Issue by suzaichuan** [kissvivi/kv-iot#2]
make docker 时出现错误如下：

Removing intermediate container 28fbfbca9ced
 ---> 6ba8f73a96eb
Step 6/14 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on
 ---> Running in 2f1de567d8ea
Removing intermediate container 2f1de567d8ea
 ---> 9d52222499ed
Step 7/14 : RUN go build -mod=vendor -ldflags "-s -w" -o build/kv-$SVC cmd/$SVC/main.go
 ---> Running in fa064370aa7a
panic: modindex.GetPackage called with empty modroot

goroutine 20 [running]:
cmd/go/internal/modindex.GetModule({0x0, 0x0})
        /usr/local/go/src/cmd/go/internal/modindex/read.go:157 +0x125
cmd/go/internal/modindex.GetPackage({0x0, 0x0}, {0xc0000c62e0, 0x1f})
        /usr/local/go/src/cmd/go/internal/modindex/read.go:135 +0x31
cmd/go/internal/modload.scanDir({0x0?, 0x18?}, {0xc0000c62e0, 0x1f}, 0x0?)
        /usr/local/go/src/cmd/go/internal/modload/load.go:2105 +0x4b
cmd/go/internal/modload.(*loader).load(0xc000136c30, {0xb2e7d0, 0xc00009a000}, 0xc000136f70)
        /usr/local/go/src/cmd/go/internal/modload/load.go:1734 +0x35f
cmd/go/internal/modload.(*loader).pkg.func1.1()
        /usr/local/go/src/cmd/go/internal/modload/load.go:1517 +0x29
cmd/go/internal/par.(*Queue).Add.func1()
        /usr/local/go/src/cmd/go/internal/par/queue.go:58 +0x7d
created by cmd/go/internal/par.(*Queue).Add
        /usr/local/go/src/cmd/go/internal/par/queue.go:56 +0x225
The command '/bin/sh -c go build -mod=vendor -ldflags "-s -w" -o build/kv-$SVC cmd/$SVC/main.go' returned a non-zero code: 2
make: *** [Makefile:54: docker_auth] Error 2
root@htgd:/disk2/iot/kv-iot# vi Makefile

**Comment by kissvivi** [comment]
建议linux环境下使用make构建，win系统下，没有试验过make，win系统可以直接用goland编辑器打开启动

**Comment by suzaichuan** [comment]
是在Ubuntu20下进行的make

**Comment by kissvivi** [comment]
我没有上传mod文件，先运行下面命令，再make
`go mod init kv-iot
go mod tidy
go mod vendor
`
